### ISSUE TITLE
глюк в дайс роллер

### ISSUE THREAD

**Issue by LaineZ** [Kotik-Wilson/C-Shrap-#1]
сделай чтобы по центру было, также чё за  7 в рандоме, если кейс на 6 кончается?

**Comment by Kotik-Wilson** [comment]
> Не шаришь в C#!

**Comment by LaineZ** [comment]
а по центру то не осилил

**Comment by LaineZ** [comment]
ну в общем это никогда не исправится - invalid, wontfix
